#!/bin/dash

mime=$(file -Lb --mime-type -- "$1")

case "$mime" in
    image/*)
        #chafa -f sixel -s "$2x$3" --animate off --polite on -t 1 --bg white "$1"
        exiftool -- "$1"
        exit $?
        ;;
    application/pdf)
        pdfinfo -- "$1"
        exit $?
        ;;
    video/*|audio/*)
        mediainfo -- "$1"
        exit $?
        ;;
    application/x-executable|application/x-sharedlib|application/x-pie-executable)
        # Disassemble binaries with objdump and view with bat
        objdump -d -M intel "$1" | bat -l asm --style=plain --paging=never --color=always
        exit $?
        ;;
    *)
        # Let bat handle all code / text-like files safely
        if file -Lb -- "$1" | grep -qi "text"; then
            bat --style=full --paging=never --color=always "$1"
        fi
        exit $?
        ;;
esac
