#!/bin/dash

mime=$(file -Lb --mime-type -- "$1")

case "$mime" in
    image/*)
        chafa -f sixel -s "$2x$3" --animate off --polite on -t 1 --bg white "$1"
        exit $?
        ;;
    application/pdf)
        pdfinfo -- "$1"
        exit $?
        ;;
    video/*|audio/*)
        mediainfo -- "$1"
        exit $?
        ;;
    *)
        # Let bat handle all code / text-like files safely
        if file -Lb -- "$1" | grep -qi "text"; then
            bat --decorations=never --paging=never --color=always "$1"
        fi
        exit $?
        ;;
esac
