#!/usr/bin/zsh

export EDITOR=vim
export NVIM_YANK=wl-copy
export NVIM_PASTE=wl-paste
export CC=clang
export CXX=clang++
export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
export DEBUGINFO_URLS="https://debuginfod.archlinux.org"
export BAT_THEME="gruvbox"
export ZEPHYR_TOOLCHAIN_VARIANT="zephyr"
export ZEPHYR_SDK_INSTALL_DIR="$HOME/.local/zephyr-sdk-1.0.1"
export GNUARMEMB_TOOLCHAIN_PATH="/home/deanr/Projects/libs/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi"
export ESPRESSIF_TOOLCHAIN_PATH="$HOME/Projects/libs/espressif/tools/xtensa-esp-elf/esp-15.2.0_20251204/xtensa-esp-elf"
export OZONE_PLATFORM=wayland
export LIBVIRT_DEFAULT_URI=qemu:///system
export JQ_COLORS="0;90:0;35:0;35:0;35:0;32:0;10:0;10:1;33"
export QT_QPA_PLATFORMTHEME="qt6ct"
export SWAY_UNSUPPORTED_GPU=true
export CMAKE_BUILD_PARALLEL_LEVEL=20
# export GCC_13_3="/tools/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi" 
# export TOOLCHAIN_PATH="$GCC_13_3"
# export PATH="$PATH:$TOOLCHAIN_PATH/bin"
# export GNUARMEMB_TOOLCHAIN_PATH="$TOOLCHAIN_PATH"

