#!/bin/zsh

if [ ! -d "${ZDOTDIR:-$HOME}/.local/share/zsh/zsh-syntax-highlighting" ]; then
    echo "Installing zsh-syntax-highlighting..."
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
        "${ZDOTDIR:-$HOME}/.local/share/zsh/zsh-syntax-highlighting"
fi

if [ ! -d "${ZDOTDIR:-$HOME}/.local/share/zsh/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions.git \
        "${ZDOTDIR:-$HOME}/.local/share/zsh/zsh-autosuggestions"
fi

# source "${ZDOTDIR:-$HOME}/.local/share/zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh"
source "${ZDOTDIR:-$HOME}/.local/share/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "${ZDOTDIR:-$HOME}/.local/share/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source <(fzf --zsh)

# Declare the variable
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[path]='fg=white,underline'
ZSH_HIGHLIGHT_STYLES[command]='fg=green'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=yellow,bold'
