# Font
font=JetBrainsMono NF medium:size=8
font-bold=JetBrainsMono NF medium:weight=bold:size=8
font-italic=JetBrainsMono NF medium:slant=italic:size=8
font-bold-italic=JetBrainsMono NF medium:weight=bold:slant=italic:size=8
dpi-aware=yes

# Terminal
term=xterm-256color

# Cursor
[cursor]
style=block
blink=no

# Transparency
[colors-dark]
alpha=0.70
cursor=282827 ebdbb2
background=282827
foreground=ebdbb2

regular0=282828
regular1=cc241d
regular2=98971a
regular3=d79921
regular4=458588
regular5=b16286
regular6=689d6a
regular7=a89984

bright0=928374
bright1=fb4934
bright2=b8bb26
bright3=fabd2f
bright4=83a598
bright5=d3869b
bright6=8ec07c
bright7=ebdbb2

# Selection
selection-foreground=282828
selection-background=928374

# URL color
urls=458588

# Scrollback (optional tuning)
[scrollback]
lines=10000

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v

# Disable bell visual noise
[bell]
system=no
visual=no
