# Font
font=JetBrainsMono NF medium:size=14
font-bold=JetBrainsMono NF medium:weight=bold:size=14
font-italic=JetBrainsMono NF medium:slant=italic:size=14
font-bold-italic=JetBrainsMono NF medium:weight=bold:slant=italic:size=14
dpi-aware=no

# Terminal
term=xterm-256color

# Cursor
[cursor]
style=block
blink=no

# Transparency
[colors-dark]
alpha=0.70
cursor=282827 ebdbb2
background=282828
foreground=d4be98

regular0=3c3836
regular1=ea6962
regular2=a9b665
regular3=d8a657
regular4=7daea3
regular5=d3869b
regular6=89b482
regular7=d4be98

bright0=3c3836
bright1=ea6962
bright2=a9b665
bright3=d8a657
bright4=7daea3
bright5=d3869b
bright6=89b482
bright7=d4be98

# Selection
selection-foreground=282828
selection-background=928374

# URL color
urls=458588

# Scrollback (optional tuning)
[scrollback]
lines=10000

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v

# Disable bell visual noise
[bell]
system=no
visual=no
