[flags]
basic = false
temperature_type = "c"
disable_click = true
show_table_scroll_position = true

[processes]
default_grouped = true
default_memory_value = true

[styles.memory]
swap_color = "Light Blue"
ram_color = "Light Cyan"
cache_color = "Light Red"

[styles]
theme = "gruvbox"
