# Night light / gamma adjustment
exec wlsunset -l 52.37 -L 4.89 -t 4000 -T 4500 -g 0.85

# Wallpaper daemon
exec LaunchSwww

# Notification daemon
exec swaync

# Idle management (lock + screen off)
exec swayidle -w \
    timeout 3000 'swaylock -f -c 000000' \
    timeout 6000 'swaymsg "output * poweroff"' \
        resume 'swaymsg "output * power on"' \
    before-sleep 'swaylock -f -c 000000'

# Auto-tiling script
exec_always autotiling
