# Keyboard settings
input "type:keyboard" {
    xkb_options caps:ctrl_modifier
    repeat_delay 250
    repeat_rate 30
}

# Mouse settings
input "type:pointer" {
    accel_profile flat
    pointer_accel 0.9
}

# Default layout
input * {
    xkb_layout us
}

# Mouse
mouse_warping none

input type:touchpad {
    tap enabled
}

bindgesture swipe:right workspace prev
bindgesture swipe:left workspace next
