bar {
    swaybar_command swaybar

    # Fallback status (if waybar not used)
    status_command ~/.config/sway/status.sh

    position top
    separator_symbol ""

    colors {
        background #282828 
        statusline #d4be98 
        separator  #d4be98 

        focused_workspace #d4be98 #d4be98 #282828 
        inactive_workspace #282828 #282828 #d4be98 
        active_workspace   #282828 #282828 #d4be98 
        urgent_workspace   #ea6962 #ea6962 #282828 
        binding_mode       #282828 #282828 #d4be98 
    }

    font pango:Jetbrains Mono Nerd Font 12
    tray_output HDMI-A-0
}
